// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as HyperProvider from "../context/HyperProvider.res.js";
import * as HyperNativeModules from "../nativeModules/HyperNativeModules.res.js";

function useHyper() {
  var match = React.useContext(HyperProvider.hyperProviderContext);
  var hyperVal = match[0];
  var initPaymentSession = function (initPaymentSheetParams) {
    var hsSdkParams_configuration = Core__Option.getOr(initPaymentSheetParams.configuration, {});
    var hsSdkParams_customBackendUrl = Caml_option.some(hyperVal.customBackendUrl);
    var hsSdkParams_publishableKey = hyperVal.publishableKey;
    var hsSdkParams_clientSecret = initPaymentSheetParams.clientSecret;
    var hsSdkParams = {
      configuration: hsSdkParams_configuration,
      customBackendUrl: hsSdkParams_customBackendUrl,
      publishableKey: hsSdkParams_publishableKey,
      clientSecret: hsSdkParams_clientSecret,
      type: "payment",
      from: "rn"
    };
    return new Promise((function (resolve, param) {
                  var responseResolve = function (arg) {
                    console.log("From RN Native module", arg);
                    resolve(hsSdkParams);
                  };
                  HyperNativeModules.initPaymentSession(hsSdkParams, responseResolve);
                }));
  };
  var presentPaymentSheet = function (paySheetParams) {
    return new Promise((function (resolve, param) {
                  var responseResolve = function (arg) {
                    var val = JSON.parse(arg);
                    resolve(val);
                  };
                  HyperNativeModules.presentPaymentSheet(paySheetParams, responseResolve);
                }));
  };
  var getCustomerDefaultSavedPaymentMethodData = function (paySheetParams) {
    return new Promise((function (resolve, param) {
                  var responseResolve = function (arg) {
                    var val = Js_dict.get(arg, "message");
                    resolve(val);
                  };
                  HyperNativeModules.getCustomerDefaultSavedPaymentMethodData(paySheetParams, responseResolve);
                }));
  };
  var getCustomerLastUsedPaymentMethodData = function (paySheetParams) {
    return new Promise((function (resolve, param) {
                  var responseResolve = function (arg) {
                    var val = Js_dict.get(arg, "message");
                    resolve(val);
                  };
                  HyperNativeModules.getCustomerLastUsedPaymentMethodData(paySheetParams, responseResolve);
                }));
  };
  var getCustomerSavedPaymentMethodData = function (paySheetParams) {
    return new Promise((function (resolve, param) {
                  var responseResolve = function (arg) {
                    var savedPMJsonArr = Js_dict.get(arg, "paymentMethods").map(function (item) {
                          return Js_dict.get(Core__Option.getOr(Js_json.decodeObject(item), {}), "message");
                        });
                    resolve(savedPMJsonArr);
                  };
                  HyperNativeModules.getCustomerSavedPaymentMethodData(paySheetParams, responseResolve);
                }));
  };
  var confirmWithCustomerDefaultPaymentMethod = function (paySheetParams) {
    return new Promise((function (resolve, param) {
                  var responseResolve = function (arg) {
                    resolve(arg);
                  };
                  HyperNativeModules.confirmWithCustomerDefaultPaymentMethod(paySheetParams, responseResolve);
                }));
  };
  var confirmWithCustomerLastUsedPaymentMethod = function (paySheetParams) {
    return new Promise((function (resolve, param) {
                  var responseResolve = function (arg) {
                    resolve(arg);
                  };
                  HyperNativeModules.confirmWithCustomerLastUsedPaymentMethod(paySheetParams, responseResolve);
                }));
  };
  return {
          initPaymentSession: initPaymentSession,
          presentPaymentSheet: presentPaymentSheet,
          getCustomerDefaultSavedPaymentMethodData: getCustomerDefaultSavedPaymentMethodData,
          getCustomerLastUsedPaymentMethodData: getCustomerLastUsedPaymentMethodData,
          getCustomerSavedPaymentMethodData: getCustomerSavedPaymentMethodData,
          confirmWithCustomerDefaultPaymentMethod: confirmWithCustomerDefaultPaymentMethod,
          confirmWithCustomerLastUsedPaymentMethod: confirmWithCustomerLastUsedPaymentMethod
        };
}

export {
  useHyper ,
}
/* react Not a pure module */
