// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as ReactNative from "react-native";

var hyperswitchDict = Belt_Option.getWithDefault(Belt_Option.flatMap(Js_dict.get(ReactNative.NativeModules, "HyperModule"), Js_json.decodeObject), {});

console.log("hyperswitch dict------>", Js_dict.get(ReactNative.NativeModules, "HyperHeadless"));

function getJsonFunWithCallbackFromKey(key) {
  var json = Js_dict.get(hyperswitchDict, key);
  if (json !== undefined) {
    return json;
  } else {
    return function (param, param$1) {
      console.log("flow here-");
    };
  }
}

function getStrFunWithCallbackFromKey(key) {
  var json = hyperswitchDict[key];
  if (json !== undefined) {
    return json;
  } else {
    return function (param, param$1) {
      
    };
  }
}

var hyperswitch_presentPaymentSheet = getJsonFunWithCallbackFromKey("presentPaymentSheet");

var hyperswitch_initHeadless = getJsonFunWithCallbackFromKey("initHeadless");

var hyperswitch_getCustomerSavedPaymentMethodData = getJsonFunWithCallbackFromKey("getCustomerSavedPaymentMethodData");

var hyperswitch = {
  presentPaymentSheet: hyperswitch_presentPaymentSheet,
  initHeadless: hyperswitch_initHeadless,
  getCustomerSavedPaymentMethodData: hyperswitch_getCustomerSavedPaymentMethodData
};

function presentPaymentSheet(requestObj, callback) {
  console.log("reaching here------", requestObj);
  hyperswitch_presentPaymentSheet(requestObj, callback);
}

function initHeadless(requestObj, callback) {
  hyperswitch_initHeadless(requestObj, callback);
}

function getCustomerSavedPaymentMethodData(requestObj, callback) {
  hyperswitch_getCustomerSavedPaymentMethodData(requestObj, callback);
}

export {
  hyperswitchDict ,
  getJsonFunWithCallbackFromKey ,
  getStrFunWithCallbackFromKey ,
  hyperswitch ,
  presentPaymentSheet ,
  initHeadless ,
  getCustomerSavedPaymentMethodData ,
}
/* hyperswitchDict Not a pure module */
