// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as ReactNative from "react-native";

var hyperswitchDict = Belt_Option.getWithDefault(Belt_Option.flatMap(Js_dict.get(ReactNative.NativeModules, "HyperModule"), Js_json.decodeObject), {});

console.log("hyperswitch dict------>", hyperswitchDict);

function getStrFunWithCallbackFromKey(key) {
  var json = Js_dict.get(hyperswitchDict, key);
  if (json !== undefined) {
    return json;
  } else {
    return function (param, param$1) {
      console.log("flow here-");
    };
  }
}

var hyperswitch = {
  presentPaymentSheet: getStrFunWithCallbackFromKey("presentPaymentSheet")
};

function presentPaymentSheet(requestObj, callback) {
  console.log("reaching here------", requestObj);
  hyperswitch.presentPaymentSheet(requestObj, callback);
}

export {
  hyperswitchDict ,
  getStrFunWithCallbackFromKey ,
  hyperswitch ,
  presentPaymentSheet ,
}
/* hyperswitchDict Not a pure module */
