// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function setData(providerState, initState) {
  var style = initState.style;
  var themes = style !== undefined ? (
      style === "AlwaysDark" ? "Dark" : (
          style === "Automatic" ? "" : (
              style === "Minimal" ? "Minimal" : (
                  style === "AlwaysLight" ? "Light" : "FlatMinimal"
                )
            )
        )
    ) : "";
  var appearance = Belt_Option.getWithDefault(initState.appearance, {});
  var newrecord = Caml_obj.obj_dup(appearance);
  return {
          configuration: {
            appearance: (newrecord.themes = themes, newrecord),
            googlePay: initState.googlePay,
            customer: {
              id: initState.customerId,
              ephemeralKeySecret: initState.customerEphemeralKeySecret
            }
          },
          publishableKey: providerState.publishableKey,
          clientSecret: initState.paymentIntentClientSecret,
          type: "payment",
          from: "rn",
          branding: initState.branding,
          locale: initState.locale
        };
}

export {
  setData ,
}
/* No side effect */
