// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Core__JSON from "@rescript/core/src/Core__JSON.res.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";

function paymentMethodItemToObjMapper(pmItem) {
  var pmDict = Core__Option.getOr(Core__JSON.Decode.object(pmItem), {});
  var pMType = Core__Option.getOr(Core__JSON.Decode.string(Core__Option.getExn(pmDict["paymentMethodType"], undefined)), "");
  var newrecord = Caml_obj.obj_dup(pmDict);
  newrecord.paymentMethodType = pMType;
  return newrecord;
}

export {
  paymentMethodItemToObjMapper ,
}
/* No side effect */
