// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

var dafaultVal = {
  publishableKey: ""
};

var hyperProviderContext = React.createContext([
      dafaultVal,
      (function (param) {
          
        })
    ]);

var make = hyperProviderContext.Provider;

var Provider = {
  make: make
};

function HyperProvider(props) {
  var __publishableKey = props.publishableKey;
  var publishableKey = __publishableKey !== undefined ? __publishableKey : "";
  var match = React.useState(function () {
        return {
                publishableKey: publishableKey
              };
      });
  var setState = match[1];
  React.useEffect((function () {
          setState(function (param) {
                return {
                        publishableKey: publishableKey
                      };
              });
        }), [publishableKey]);
  var setState$1 = React.useCallback((function (val) {
          setState(function (param) {
                return val;
              });
        }), [setState]);
  return JsxRuntime.jsx(make, {
              value: [
                match[0],
                setState$1
              ],
              children: props.children
            });
}

var make$1 = HyperProvider;

export {
  dafaultVal ,
  hyperProviderContext ,
  Provider ,
  make$1 as make,
}
/* hyperProviderContext Not a pure module */
