// Generated by ReScript, PLEASE EDIT WITH CARE

import * as HyperProvider from "./HyperProvider.res.js";

var HyperProvider$1 = HyperProvider.make;

export {
  HyperProvider$1 as HyperProvider,
}
/* HyperProvider Not a pure module */
