// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ReactNative from "react-native";
import * as JsxRuntime from "react/jsx-runtime";

function HyperProvider(props) {
  return JsxRuntime.jsx(ReactNative.View, {
              children: Caml_option.some(JsxRuntime.jsx(ReactNative.Text, {
                        children: "raect"
                      }))
            });
}

var make = HyperProvider;

export {
  make ,
}
/* react-native Not a pure module */
